// SPDX-FileCopyrightText: © 2026 Olof Johansson
// SPDX-License-Identifier: MIT

//! Host-side mirror of the M3 (#69) virtio-mmio register-file engine
//! layout in `brisc-firmware/include/virtio_layout.h`.
//!
//! The BRISC firmware lays out 16 virtio register files (4 L2CPUs ×
//! 4 devices) in the picked Tensix tile's L1 starting at
//! `REGS_BASE = 0x0001_0000`. The host (and eventually the L2CPU's
//! retargeted small TLB, see #70) reads/writes these via the chip
//! TLB on the picker tile. The constants here MUST match the
//! firmware header — the hardware-test path verifies them by
//! reading `MAGIC_VALUE` at the expected offsets.
//!
//! Module-wide `#![allow(dead_code)]` — wire-format constants are
//! intentionally retained even when the current crate path doesn't
//! reach all of them.
#![allow(dead_code)]

/// The embedded M3 firmware bytes, produced by
/// `brisc-firmware/Makefile` and surfaced via `build.rs`.
pub const VIRTIO_FIRMWARE: &[u8] = include_bytes!(env!("BRISC_VIRTIO_BIN"));

// `FW_BUILD_ID` is generated by `build.rs` (mirroring the Makefile's
// algorithm) and embedded as the upper 24 bits of
// `BRISC_VIRTIO_FW_VERSION` on the firmware side. The daemon's
// `adopt_running` refuses to take over a chip-side BRISC whose
// build_id doesn't match — the "daemon was rebuilt with new firmware
// sources but the chip still has the prior build" case.
include!(concat!(env!("OUT_DIR"), "/fw_build_id.rs"));

// ----- L1 layout -----

pub const CODE_BASE: u32 = 0x0000_0000;
pub const CODE_SIZE: u32 = 0x0000_4000;

pub const STATS_BASE: u32 = 0x0000_4000;
pub const STATS_SIZE: u32 = 0x0000_1000;

pub const REGS_BASE: u32 = 0x0001_0000;
pub const REGS_PER_DEV: u32 = 0x0000_1000;

pub const NUM_L2CPUS: u32 = 4;
/// Eight device slots per L2CPU. Six are populated: blk / net / console
/// / rng (the original four) plus two extra blk slots (BLK1 / BLK2)
/// used for the cloud-init NoCloud seed (#82) and a persistent data
/// volume (#81). The remaining two slots are unused.
///
/// The bump from 4 to 8 (rather than 6) keeps the value a power of
/// two so `slot % DEVS_PER_L2CPU` stays a bitmask AND on the BRISC
/// firmware side — modulo by a non-power-of-two would generate an
/// `__umodsi3` libgcc call the bare-metal toolchain doesn't link.
///
/// Mirrored in `BRISC_VIRTIO_DEVS_PER_L2CPU` in
/// `brisc-firmware/include/virtio_layout.h`. SHADOW_BASE moved to
/// 0x40000 to clear the larger reg-file region — see
/// `_LAYOUT_INVARIANTS` below.
pub const DEVS_PER_L2CPU: u32 = 8;
pub const NUM_SLOTS: u32 = NUM_L2CPUS * DEVS_PER_L2CPU;

pub const PER_L2CPU_WINDOW_SIZE: u32 = DEVS_PER_L2CPU * REGS_PER_DEV;

// ----- Device-index assignment within an L2CPU's window -----

pub const DEV_BLK: u32 = 0;
pub const DEV_NET: u32 = 1;
pub const DEV_CONSOLE: u32 = 2;
pub const DEV_RNG: u32 = 3;
/// Second virtio-blk slot — used for the cloud-init NoCloud seed
/// (serial="cidata") and as the first attach surface for an
/// operator-supplied data disk.
pub const DEV_BLK1: u32 = 4;
/// Third virtio-blk slot — additional operator-supplied data disk.
pub const DEV_BLK2: u32 = 5;

#[inline]
pub fn slot(l2cpu_idx: u32, device_idx: u32) -> u32 {
    l2cpu_idx * DEVS_PER_L2CPU + device_idx
}

#[inline]
pub fn slot_regs_base(slot: u32) -> u32 {
    REGS_BASE + slot * REGS_PER_DEV
}

#[inline]
pub fn l2cpu_window_base(l2cpu_idx: u32) -> u32 {
    REGS_BASE + l2cpu_idx * PER_L2CPU_WINDOW_SIZE
}

// ----- Virtio MMIO register offsets (virtio 1.2 §4.2.2) -----

pub const MMIO_MAGIC_VALUE: u32 = 0x000;
pub const MMIO_VERSION: u32 = 0x004;
pub const MMIO_DEVICE_ID: u32 = 0x008;
pub const MMIO_VENDOR_ID: u32 = 0x00c;
pub const MMIO_DEVICE_FEATURES: u32 = 0x010;
pub const MMIO_DEVICE_FEATURES_SEL: u32 = 0x014;
pub const MMIO_SW_IMPL: u32 = 0x018;
pub const MMIO_SEL_GENERATION: u32 = 0x01c;
pub const MMIO_DRIVER_FEATURES: u32 = 0x020;
pub const MMIO_DRIVER_FEATURES_SEL: u32 = 0x024;
pub const MMIO_QUEUE_SEL: u32 = 0x030;
pub const MMIO_QUEUE_NUM_MAX: u32 = 0x034;
pub const MMIO_QUEUE_NUM: u32 = 0x038;
pub const MMIO_QUEUE_READY: u32 = 0x044;
pub const MMIO_QUEUE_NOTIFY: u32 = 0x050;
pub const MMIO_INTERRUPT_STATUS: u32 = 0x060;
pub const MMIO_INTERRUPT_ACK: u32 = 0x064;
pub const MMIO_STATUS: u32 = 0x070;
pub const MMIO_QUEUE_DESC_LOW: u32 = 0x080;
pub const MMIO_QUEUE_DESC_HIGH: u32 = 0x084;
pub const MMIO_QUEUE_DRIVER_LOW: u32 = 0x090;
pub const MMIO_QUEUE_DRIVER_HIGH: u32 = 0x094;
pub const MMIO_QUEUE_DEVICE_LOW: u32 = 0x0a0;
pub const MMIO_QUEUE_DEVICE_HIGH: u32 = 0x0a4;
pub const MMIO_CONFIG_GENERATION: u32 = 0x0fc;
pub const MMIO_CONFIG: u32 = 0x100;

// ----- Constants the firmware writes -----

pub const MAGIC: u32 = 0x7472_6976; // "virt" little-endian
const _MAGIC_IS_VIRT_LE: () = assert!(MAGIC == u32::from_le_bytes([b'v', b'i', b'r', b't']));
pub const VERSION: u32 = 2;
pub const VENDOR_ID: u32 = 0x5554_4254; // "TBTU" — keep in sync with virtio.c

pub const VIRTIO_ID_NET: u32 = 1;
pub const VIRTIO_ID_BLOCK: u32 = 2;
pub const VIRTIO_ID_CONSOLE: u32 = 3;
pub const VIRTIO_ID_ENTROPY: u32 = 4;

/// Must match `BRISC_VIRTIO_QUEUE_NUM_MAX` in
/// `brisc-firmware/include/virtio_layout.h` — the diagnostic in
/// `main.rs::cmd_engine_probe` reads QUEUE_NUM_MAX off the chip and
/// asserts it equals this constant.
pub const QUEUE_NUM_MAX: u32 = 256;

// ----- Status bits (virtio 1.2 §2.1) -----

pub const STATUS_ACKNOWLEDGE: u32 = 1;
pub const STATUS_DRIVER: u32 = 2;
pub const STATUS_DRIVER_OK: u32 = 4;
pub const STATUS_FEATURES_OK: u32 = 8;
pub const STATUS_DEVICE_NEEDS_RESET: u32 = 64;
pub const STATUS_FAILED: u32 = 128;

// ----- Stats page offsets (must match firmware's STATS_OFF_*) -----

pub const STATS_OFF_VERSION: u32 = 0x000;
pub const STATS_OFF_MAGIC: u32 = 0x004;
pub const STATS_OFF_HEARTBEAT: u32 = 0x008;
pub const STATS_OFF_STATUS_CHANGES: u32 = 0x010;
pub const STATS_OFF_SEL_CHANGES: u32 = 0x014;
pub const STATS_OFF_NOTIFY_EVENTS: u32 = 0x018;
pub const STATS_OFF_READY_EVENTS: u32 = 0x01c;
pub const STATS_OFF_LAST_NOTIFY: u32 = 0x020;
// 0x024 / 0x028 / 0x02c retired with the V1 kick + completion rings
// (#188): STATS_OFF_COMPL_EVENTS, STATS_OFF_LAST_COMPL,
// STATS_OFF_KICK_DROPS. Reserved — don't reuse without bumping
// PROTOCOL_VERSION.
/// Cumulative count of QUEUE_SEL changes BRISC processed while the
/// previous SEL's QUEUE_READY was still 1 — i.e. the race window
/// the M7.2 fix (#71, commit 1345f3e) was designed to close re-opened.
/// During that window a stock kernel doing
/// `writel(SEL=N+1); readl(QUEUE_READY)` back-to-back can read the
/// stale 1 and bail with -ENOENT. Bumped by the firmware's
/// `handle_queue_sel_change`. Mirrored on the firmware side as
/// `STATS_OFF_SEL_READY_RACES` in `brisc-firmware/virtio.c`.
pub const STATS_OFF_SEL_READY_RACES: u32 = 0x030;
/// #124 BRISC timing probe (BRISC mcycle CSR samples). All in cycles
/// at the BRISC clock — convert to ns by dividing by AICLK in GHz
/// (1.35 GHz at MAX_AI_CLK ⟹ ~0.74 ns/cycle).
///
/// `MAX_SWEEP_CYCLES`: worst-case top-of-main-loop to top-of-main-loop
/// duration since stats reset. The relevant number for racing the
/// kernel's `writel(QUEUE_SEL); readl(QUEUE_READY)` gap.
///
/// `MAX_SEL_PATH_CYCLES`: worst-case `handle_queue_sel_change` entry
/// to right-after-FENCE_W (the moment QUEUE_READY=0 is published).
/// The duration BRISC holds the kernel waiting on its readl response.
///
/// `LAST_SWEEP_CYCLES`: most recent sweep period. Useful when MAX
/// looks suspicious (e.g., a single early outlier from cold-cache
/// effects swamps everything).
pub const STATS_OFF_MAX_SWEEP_CYCLES: u32 = 0x034;
pub const STATS_OFF_MAX_SEL_PATH_CYCLES: u32 = 0x038;
pub const STATS_OFF_LAST_SWEEP_CYCLES: u32 = 0x03c;
/// #120 atomic capture stats. `READY_CAPTURE_SEL_RACES` counts cases
/// where the kernel advanced SEL between BRISC's setup-field reads
/// and BRISC's post-read SEL re-check (mixed-queue snapshot, discarded).
/// `QUEUE_SETUPS` counts successful captures (queue activations);
/// `QUEUE_TEARDOWNS` counts READY=0 events. Together they replace the
/// lumped READY_EVENTS for "how many virtio commands has BRISC actually
/// processed" — useful both as forward-progress evidence and as a
/// soak-time sanity check that capture isn't quietly losing setups.
pub const STATS_OFF_READY_CAPTURE_SEL_RACES: u32 = 0x04c;
pub const STATS_OFF_QUEUE_SETUPS: u32 = 0x050;
pub const STATS_OFF_QUEUE_TEARDOWNS: u32 = 0x054;
/// #155 BRISC OLD-sel rescue captures. Mirrors the firmware
/// `STATS_OFF_BRISC_OLD_SEL_RESCUE`. Fires when BRISC observes a SEL
/// change with no prior successful capture for the old sel — snapshots
/// the still-visible kernel writes for old sel into shadow.
pub const STATS_OFF_BRISC_OLD_SEL_RESCUE: u32 = 0x06c;
/// #132 DEVICE_FEATURES_SEL change observations from TRISC1.
pub const STATS_OFF_DEV_FEAT_SEL_CHANGES: u32 = 0x058;
/// Sweep-cycle histogram. Each bucket counts iterations whose sweep
/// fell in the bucket's range (in BRISC cycles). Useful for
/// distinguishing typical sweep cost from one-shot outliers like
/// `init_device` running on STATUS=0 (~1200 cycles in a 320-store
/// wipe, lands once per probe round per slot).
/// Steady-state sweep max — same as `STATS_OFF_MAX_SWEEP_CYCLES`
/// but excludes iters where `init_device` fired (one-shot ~1240-cycle
/// wipe on STATUS=0). This is the race-relevant max.
pub const STATS_OFF_MAX_STEADY_SWEEP_CYCLES: u32 = 0x068;

// ----- Per-queue shadow region (BRISC L1, M5.5b firmware) -----
//
// The firmware shadows guest writes to the per-queue setup
// registers (QUEUE_NUM + DESC/DRIVER/DEVICE addresses) into this
// region, indexed by `(slot, queue_idx)`. The data plane reads
// from here on each kick to know which avail/desc/used rings to
// walk in guest DRAM. These offsets MUST match the C firmware's
// `SHADOW_Q_OFF_*` constants in `brisc-firmware/virtio.c`.

/// Base of the per-slot shadow region. Sits immediately after the
/// reg-file region so writes by BRISC to reg files and shadow stay in
/// the same Tensix L1 bank — banked L1 doesn't enforce store ordering
/// across banks, even with `fence w,w`, so a shadow write followed by
/// a kick-ring write (CTRL_BASE = 0x5000) becomes visible to the
/// daemon out-of-order whenever the two regions land on different
/// banks. With 32 reg files (4 L2CPUs × 8 devs × 4 KiB) the reg region
/// ends at 0x30000; SHADOW_BASE picks up there. Originally 0x20000
/// when there were only 16 reg files; the bump to 0x30000 keeps
/// shadow contiguous with reg files. Mirrored on the firmware side as
/// `SHADOW_BASE` in `brisc-firmware/virtio.c`.
pub const SHADOW_BASE: u32 = 0x0003_0000;
pub const SHADOW_PER_DEVICE: u32 = 0x400;
pub const SHADOW_PER_QUEUE: u32 = 0x40;
pub const SHADOW_Q_OFF_NUM: u32 = 0x00;
pub const SHADOW_Q_OFF_READY: u32 = 0x04;
pub const SHADOW_Q_OFF_DESC_LO: u32 = 0x08;
pub const SHADOW_Q_OFF_DESC_HI: u32 = 0x0c;
pub const SHADOW_Q_OFF_DRIVER_LO: u32 = 0x10;
pub const SHADOW_Q_OFF_DRIVER_HI: u32 = 0x14;
pub const SHADOW_Q_OFF_DEVICE_LO: u32 = 0x18;
pub const SHADOW_Q_OFF_DEVICE_HI: u32 = 0x1c;

#[inline]
pub fn shadow_queue_addr(slot: u32, queue_idx: u32, off: u32) -> u32 {
    SHADOW_BASE + slot * SHADOW_PER_DEVICE + queue_idx * SHADOW_PER_QUEUE + off
}

// Per-slot snapshot region inside the shadow block. BRISC's
// `poll_one_device` snapshots the visible regs here so subsequent
// iterations can detect "did the kernel write anything since last
// poll?" via diff. The daemon reads `SNAP_OFF_STATUS` to surface
// per-device "kernel completed probe" signals (#123 debugging).
pub const SNAP_BASE_OFF: u32 = 0x200;
pub const SNAP_OFF_STATUS: u32 = 0x00;

#[inline]
pub fn snap_addr(slot: u32, off: u32) -> u32 {
    SHADOW_BASE + slot * SHADOW_PER_DEVICE + SNAP_BASE_OFF + off
}

pub const STATS_MAGIC_LOADED: u32 = 0x0000_B155;

// ----- Per-device queue counts (must match firmware constants) -----

pub const QUEUES_BLK: u32 = 1;
pub const QUEUES_NET: u32 = 2;
pub const QUEUES_CONSOLE: u32 = 2;
pub const QUEUES_RNG: u32 = 1;

#[inline]
pub fn num_queues_for_device(device_idx: u32) -> u32 {
    match device_idx {
        DEV_BLK | DEV_BLK1 | DEV_BLK2 => QUEUES_BLK,
        DEV_NET => QUEUES_NET,
        DEV_CONSOLE => QUEUES_CONSOLE,
        DEV_RNG => QUEUES_RNG,
        _ => 0,
    }
}

#[inline]
pub fn device_id_for_index(device_idx: u32) -> u32 {
    match device_idx {
        DEV_BLK | DEV_BLK1 | DEV_BLK2 => VIRTIO_ID_BLOCK,
        DEV_NET => VIRTIO_ID_NET,
        DEV_CONSOLE => VIRTIO_ID_CONSOLE,
        DEV_RNG => VIRTIO_ID_ENTROPY,
        _ => 0,
    }
}

/// VIRTIO_F_VERSION_1 lives at bit 32 of the 64-bit feature space —
/// bit 0 of the high half. Mirrors `VIRTIO_F_VERSION_1_HIGH_BIT` in
/// `brisc-firmware/virtio.c`.
pub const VIRTIO_F_VERSION_1_HIGH_BIT: u32 = 0x0000_0001;
/// VIRTIO_NET_F_MAC lives at bit 5 of the low half (features[0]).
/// Mirrors `VIRTIO_NET_F_MAC_BIT` in the firmware.
pub const VIRTIO_NET_F_MAC_BIT: u32 = 1 << 5;

/// Bits 0..31 (DEVICE_FEATURES_SEL=0) of the per-slot feature space.
/// Mirrors `DEVICE_TEMPLATE[].dev_feat_low` in the firmware.
#[inline]
pub fn dev_feat_low_for_index(device_idx: u32) -> u32 {
    match device_idx {
        DEV_NET => VIRTIO_NET_F_MAC_BIT,
        // Other populated slots advertise no low-half bits today.
        DEV_BLK | DEV_BLK1 | DEV_BLK2 | DEV_CONSOLE | DEV_RNG => 0,
        _ => 0,
    }
}

/// Bits 32..63 (DEVICE_FEATURES_SEL=1) of the per-slot feature space.
/// Today every populated slot advertises VIRTIO_F_VERSION_1; unused
/// slots advertise nothing.
#[inline]
pub fn dev_feat_high_for_index(device_idx: u32) -> u32 {
    match device_idx {
        DEV_BLK | DEV_BLK1 | DEV_BLK2 | DEV_NET | DEV_CONSOLE | DEV_RNG => {
            VIRTIO_F_VERSION_1_HIGH_BIT
        }
        _ => 0,
    }
}

// ----- Compile-time sanity -----

const _LAYOUT_INVARIANTS: () = {
    // Stats lives between code and the reg files; reg files don't
    // overlap with the shadow region.
    assert!(STATS_BASE >= CODE_BASE + CODE_SIZE);
    assert!(REGS_BASE >= STATS_BASE + STATS_SIZE);
    // Cross-module check: the control region (kick + completion
    // rings, hello/hello-ack, active-slots bitmap) lives between
    // STATS and REGS. A future bump of CTRL_SIZE that sneaks past
    // REGS_BASE would silently alias the kick ring onto the virtio
    // reg files. Pin both edges.
    assert!(crate::tensix_proto::CTRL_BASE >= STATS_BASE + STATS_SIZE);
    assert!(crate::tensix_proto::CTRL_BASE + crate::tensix_proto::CTRL_SIZE <= REGS_BASE);
    // 32 reg files (4 L2CPUs × 8 devices, 6 populated + 2 padding) of
    // 4 KiB each = 128 KiB, occupying [REGS_BASE, REGS_BASE+0x20000).
    assert!(NUM_SLOTS * REGS_PER_DEV == 32 * 0x1000);
    // Each L2CPU's window is DEVS_PER_L2CPU contiguous device reg files.
    assert!(PER_L2CPU_WINDOW_SIZE == DEVS_PER_L2CPU * REGS_PER_DEV);
    // DEVS_PER_L2CPU must stay a power of two so the firmware's
    // `slot % DEVS_PER_L2CPU` is a bitmask AND, not an __umodsi3 call.
    assert!(DEVS_PER_L2CPU.is_power_of_two());
    // Shadow region must sit above the reg-file region.
    assert!(SHADOW_BASE >= REGS_BASE + NUM_SLOTS * REGS_PER_DEV);
    // Shadow must end before BRISC_UART_BASE (0x40000 in
    // uart_layout.h) — a previous bump put SHADOW at 0x40000 which
    // overlapped the host-facing UART register file and caused
    // BRISC's shadow writes to land on top of UART regs (and vice
    // versa). The kick poller saw partial avail addresses on every
    // boot. Mirrored on the firmware side as `SHADOW_BASE` in
    // `brisc-firmware/virtio.c`.
    assert!(SHADOW_BASE + NUM_SLOTS * SHADOW_PER_DEVICE <= 0x0004_0000);

    // V2 layout cross-pin (#187). `tensix_proto::_V2_NUM_SLOTS` is
    // hard-coded as 32 to keep that module self-contained; this pins
    // it to `NUM_SLOTS` so a future change here can't silently desync
    // the V2 dirty / processed arrays.
    assert!(NUM_SLOTS == 32);
    assert!(
        crate::tensix_proto::CTRL_OFF_DIRTY + NUM_SLOTS * crate::tensix_proto::MAX_QUEUES_PER_SLOT
            <= crate::tensix_proto::CTRL_OFF_PROCESSED
    );
    assert!(
        crate::tensix_proto::CTRL_OFF_PROCESSED
            + NUM_SLOTS * crate::tensix_proto::MAX_QUEUES_PER_SLOT * 2
            <= crate::tensix_proto::CTRL_OFF_STATE_LOG
    );
    assert!(crate::tensix_proto::CTRL_OFF_V2_END <= crate::tensix_proto::CTRL_SIZE);
};

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn slot_indices_match_layout() {
        // 8 slots per L2CPU (6 populated + 2 padding for power-of-2):
        // blk / net / console / rng / blk1 / blk2 / unused / unused.
        assert_eq!(slot(0, DEV_BLK), 0);
        assert_eq!(slot(0, DEV_RNG), 3);
        assert_eq!(slot(0, DEV_BLK1), 4);
        assert_eq!(slot(0, DEV_BLK2), 5);
        // L2CPU 1's blk skips L2CPU 0's two padding slots (6, 7).
        assert_eq!(slot(1, DEV_BLK), 8);
        // Highest populated slot: L2CPU 3, BLK2.
        assert_eq!(slot(3, DEV_BLK2), 29);
    }

    #[test]
    fn slot_regs_base_matches_layout() {
        assert_eq!(slot_regs_base(0), 0x10000);
        assert_eq!(slot_regs_base(1), 0x11000);
        // Last slot (NUM_SLOTS - 1 = 31): REGS_BASE + 31*0x1000 = 0x2F000.
        assert_eq!(slot_regs_base(NUM_SLOTS - 1), 0x2F000);
    }

    #[test]
    fn l2cpu_windows_are_disjoint_and_contiguous() {
        for cpu in 0..NUM_L2CPUS {
            let base = l2cpu_window_base(cpu);
            assert_eq!(base, REGS_BASE + cpu * PER_L2CPU_WINDOW_SIZE);
            let blk_slot_base = slot_regs_base(slot(cpu, DEV_BLK));
            assert_eq!(blk_slot_base, base);
            let rng_slot_base = slot_regs_base(slot(cpu, DEV_RNG));
            assert_eq!(rng_slot_base, base + 3 * REGS_PER_DEV);
        }
    }

    #[test]
    fn embedded_firmware_is_nonempty_and_aligned() {
        assert!(!VIRTIO_FIRMWARE.is_empty());
        // First 4 bytes must be the entry stub `j main_entry` from
        // start.S, encoded as `0x0800006f`. If this changes the M3
        // firmware probably broke its calling convention.
        let entry = u32::from_le_bytes([
            VIRTIO_FIRMWARE[0],
            VIRTIO_FIRMWARE[1],
            VIRTIO_FIRMWARE[2],
            VIRTIO_FIRMWARE[3],
        ]);
        assert_eq!(entry, 0x0800_006f);
    }
}
